version: '3'
services:
  inventory:
    build: ./inventory
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    volumes:
      - ./inventory:/src
    env_file:
      - .env
    depends_on:
      - redis
    
  payment:
    build: ./payment
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8002:8000
    volumes:
      - ./payment:/src
    env_file:
      - .env
    depends_on:
      - redis
    
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
      
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/src
    depends_on:
      - inventory
      - payment
