version: '3'
services:
  inventory:
    build: ./inventory
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    volumes:
      - ./inventory:/src
    env_file:
      - .env
    
  payment:
    build: ./payment
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8002:8000
    volumes:
      - ./payment:/src
    env_file:
      - .env
    
